#sed -i '1i src-git haibo https://github.com/haiibo/openwrt-packages' feeds.conf.default
#sed -i '$a src-git lede https://github.com/coolsnowwolf/packages' feeds.conf.default
#sed -i '$a src-git redsocks2 https://github.com/sdhz153/redsocks2' feeds.conf.default
#sed -i '$a src-git smpackage https://github.com/Mike-qian/openwrt-packages' feeds.conf.default
#sed -i '$a src-git bypass https://github.com/tianiue/luci-app-bypass' feeds.conf.default
#sed -i '1i src-git kiddin9 https://github.com/kiddin9/openwrt-packages.git' feeds.conf.default
#sed -i '1i src-git kenzok81 https://github.com/kenzok8/openwrt-packages.git' feeds.conf.default
#sed -i '1i src-git kenzok82 https://github.com/kenzok8/small-package.git' feeds.conf.default
#sed -i '1i src-git kenzok83 https://github.com/kenzok8/small.git' feeds.conf.default
#sed -i '1i src-git lionel-package https://github.com/Lienol/openwrt-package.git' feeds.conf.default
